#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const toml = require('@iarna/toml');

const rootDir = path.join(__dirname, '..');

console.log('🔧 Syncing version across all files...');

// Read version from version.json
const versionJsonPath = path.join(rootDir, 'version.json');
if (!fs.existsSync(versionJsonPath)) {
  console.error('❌ version.json not found at:', versionJsonPath);
  process.exit(1);
}

const versionData = JSON.parse(fs.readFileSync(versionJsonPath, 'utf8'));
const { version, name, identifier, description } = versionData;

console.log(`📦 Updating to version: ${version}`);

// Helper function to update JSON files
function updateJsonFile(filePath, updateCallback) {
  try {
    const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    updateCallback(content);
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
    console.log(`✅ Updated ${path.basename(filePath)}`);
  } catch (error) {
    console.error(`❌ Error updating ${path.basename(filePath)}:`, error.message);
  }
}

// 1. Update package.json
updateJsonFile(path.join(rootDir, 'package.json'), (pkg) => {
  pkg.version = version;
});

// 2. Update tauri.conf.json
updateJsonFile(path.join(rootDir, 'src-tauri', 'tauri.conf.json'), (tauriConf) => {
  tauriConf.version = version;
  tauriConf.productName = name;
  tauriConf.identifier = identifier;
  
  if (tauriConf.app?.windows?.[0]) {
    tauriConf.app.windows[0].title = `${name} (v${version})`;
  }
});

// 3. Update Cargo.toml
try {
  const cargoTomlPath = path.join(rootDir, 'src-tauri', 'Cargo.toml');
  const cargoContent = fs.readFileSync(cargoTomlPath, 'utf8');
  const cargoToml = toml.parse(cargoContent);
  
  if (cargoToml.package) {
    cargoToml.package.version = version;
    
    if (description) {
      cargoToml.package.description = description;
    }
  }
  
  fs.writeFileSync(cargoTomlPath, toml.stringify(cargoToml));
  console.log('✅ Updated Cargo.toml');
} catch (error) {
  console.error('❌ Error updating Cargo.toml:', error.message);
}

// 4. Optional: Create version file for Rust
try {
  const srcDir = path.join(rootDir, 'src-tauri', 'src');
  const versionRsPath = path.join(srcDir, 'version.rs');
  
  if (!fs.existsSync(srcDir)) {
    console.log('⚠️  src directory does not exist, skipping version.rs creation');
  } else {
    const versionRsContent = `// Auto-generated file - do not edit manually
// This file is generated by scripts/sync-version.js

pub const APP_VERSION: &str = "${version}";
pub const APP_NAME: &str = "${name}";
pub const APP_IDENTIFIER: &str = "${identifier}";`;
    
    fs.writeFileSync(versionRsPath, versionRsContent);
    console.log('✅ Created/updated version.rs for Rust');
  }
} catch (error) {
  console.log('⚠️  Could not create version.rs:', error.message);
}

console.log('🎉 Version sync completed successfully!');
console.log(`📋 Summary: Version ${version} synced across all configuration files.`);