// Auto-generated file - do not edit manually
// This file is generated by scripts/sync-version.js

pub const APP_VERSION: &str = "0.1.3";
pub const APP_NAME: &str = "Chords LSL Visualizer";
pub const APP_IDENTIFIER: &str = "com.upsidedownlabs.chords";